export const texts = [
  {
    identifier: "tshirtname",
    text: "Remco G.",
    fontSize: 45,
    fontFamily: "Blue Waffle",
    color: "#E3B000",
    isUpperCase: true,
    position: null,
    horizontalPosition: "center",
    verticalPosition: null,
    distanceFromTopPercentage: 35,
    distanceFromLeftPercentage: 50,
  },
  {
    identifier: "tshirtnumber",
    text: "NUMBER 10",
    fontSize: 35,
    fontFamily: "Palette Mosaic",
    color: "#E3B000",
    isUpperCase: true,
    position: null,
    horizontalPosition: "center",
    verticalPosition: null,
    distanceFromTopPercentage: 25,
    distanceFromLeftPercentage: 50,
  },
];
export const texts2 = [{"text":"Text Here","fontSizeRatio":"8","fontFamily":"Rounded Mplus","color":"#fff","fontWeight":"700","shiftHorizontal":"0","fixedStart":"0","shiftVertical":0,"rotateDeg":"0","curvature":0,"maxLength":8,"letterSpacing":"0"}]

export const texts3 = [
  {
    identifier: "sheetname",
    text: "Lots of text here about • 纳伯 纳伯 纳伯 • مرحبا ما الأخبار • это текст •",
    fontSize: 45,
    fontSizeRatio: 2,
    fontFamily: "Myriad Roman",
    color: "#000",
    isUpperCase: true,
    isLowerCase: false,
    position: null,
    horizontalPosition: "",
    verticalPosition: "",
    distanceFromTopPercentage: 50.5,
    distanceFromLeftPercentage: 50,
    maxLength: 8,
    style: "vertical",
    radiusRaito: 30,
  },
];
export const texts4 = [
  {
    identifier: "sheetname",
    text: "Paw to my hart",
    fontSize: 45,
    fontSizeRatio: 17,
    fontFamily: "Freescript",
    color: "#000",
    isUpperCase: false,
    isLowerCase: false,
    position: null,
    horizontalPosition: "center",
    verticalPosition: "",
    distanceFromTopPercentage: 72,
    distanceFromLeftPercentage: 20,
    maxLength: 8,
    style: "vertical",
    radiusRaito: null,
    fontWeight: "Bold",
  },
];
export const texts5 = [
  {
    identifier: "sheetname",
    text: "Butterfly",
    fontSize: 45,
    fontSizeRatio: 23,
    fontFamily: "Acto Black",
    color: "#fff",
    isUpperCase: true,
    isLowerCase: false,
    position: null,
    horizontalPosition: "",
    verticalPosition: "",
    distanceFromTopPercentage: 100,
    distanceFromLeftPercentage: 3,
    maxLength: 8,
    style: "vertical",
    radiusRaito: null,
    fontWeight: "Bold",
    maxLengthAllowed: true,
  },
  {
    identifier: "sheetname",
    text: "Beautiful like a",
    fontSize: 45,
    fontSizeRatio: 13,
    fontFamily: "Golden Plains",
    color: "#000",
    isUpperCase: false,
    isLowerCase: false,
    position: null,
    horizontalPosition: "",
    verticalPosition: "",
    distanceFromTopPercentage: 80,
    distanceFromLeftPercentage: 4,
    maxLength: 8,
    style: "vertical",
    radiusRaito: null,
    fontWeight: "Normal",
  },
];
export const texts6 = [
  {
    identifier: "sheetname",
    text: "Happy Unicorn",
    fontSize: 45,
    fontSizeRatio: 23,
    fontFamily: "Acto Black",
    color: "#fff",
    isUpperCase: true,
    isLowerCase: false,
    position: null,
    horizontalPosition: "",
    verticalPosition: "",
    distanceFromTopPercentage: 100,
    distanceFromLeftPercentage: 3,
    maxLength: 8,
    style: "curved",
    radiusRaito: null,
    fontWeight: "Bold",
    maxLengthAllowed: true, //if true we should be able to make text smaller
  },
];
